"""Is_LLM

Revision ID: 14a0fb5c1193
Revises: e1a98f0414a9
Create Date: 2025-02-03 22:11:47.409172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a0fb5c1193'
down_revision = 'e1a98f0414a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_llm', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('is_llm')

    # ### end Alembic commands ###
