"""Run status

Revision ID: 400320acc80b
Revises: 72f4cc84b8ca
Create Date: 2025-01-04 03:55:35.170745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400320acc80b'
down_revision = '72f4cc84b8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
