"""peft params

Revision ID: cc128fd6c048
Revises: 14a0fb5c1193
Create Date: 2025-02-14 10:49:13.154616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc128fd6c048'
down_revision = '14a0fb5c1193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peft_r', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peft_alpha', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peft_dropout', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('peft_dropout')
        batch_op.drop_column('peft_alpha')
        batch_op.drop_column('peft_r')

    # ### end Alembic commands ###
