"""change foreign key

Revision ID: e1a98f0414a9
Revises: 179f8d7f483b
Create Date: 2025-01-16 12:53:58.176592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a98f0414a9'
down_revision = '179f8d7f483b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('runs_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'runs', ['run_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('run_id')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_foreign_key('runs_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
